/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package draw2;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.Timer;
/**
 *
 * @author ASUS
 */
public class DrawPanel extends JPanel implements ActionListener {
    private Color drawColor=new Color(0,255,0);
    Timer timer;
    

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
        super.setSize(300,300);
        this.setFocusable(true);
        this.addKeyListener(new MyKeyAdapter());
        timer=new Timer(150,this);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
protected void paintComponent(Graphics g)
{
        g.setColor(drawColor);
        g.fillOval(200, 150, 100, 100);
}
    @Override
    public void actionPerformed(ActionEvent e) {
        repaint();
    }

    void SetColor(Color c) {
        
       drawColor=c;
       repaint();
    }

   
    
public class MyKeyAdapter extends KeyAdapter
{
@Override
public void keyPressed(KeyEvent e){
    switch (e.getKeyCode()){
        case KeyEvent.VK_LEFT:
            drawColor=new Color(0,0,255);
            break;
        case KeyEvent.VK_RIGHT:
            drawColor=new Color(255,0,0);
            break;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
}